### ISSUE TITLE
An alternative way for "exploring" images

### ISSUE THREAD

**Issue by jordymeow** [laurenashpole/react-inner-image-zoom#10]
Hi,

This little module is really nice. 

Personally, I would love it if we could have an alternative method (through an attribute) that will allow users to click to zoom, then _drag_ the zoomed image around. One simple click would un-zoom.

An example of the _dragging_ can be found here: https://www.cssscript.com/demo/drag-move-mouse-wheel-zoom/. 

It would allow users to zoom on details of an image, and perform some other actions related to it somewhere else at the same time. 

Thanks a lot for considering this :)

**Comment by laurenashpole** [comment]
@jordymeow Hey, thanks for the new use case! I'm never sure what extra functionality people would actually find helpful.

It seems like it might be possible to add dragging by extending the current touch device behavior so it might not require too many changes. I'll take a look in the next couple days to see if I can get it working.

**Comment by jordymeow** [comment]
Thank you @laurenashpole, it's the only thing which is missing to this nice little module :) I am looking forward to it.

**Comment by laurenashpole** [comment]
Hey @jordymeow. Just wanted to let you know I just released an update (v.1.1.0) with a non-touch device drag option. You can try it by passing the prop `moveType` with the value `drag`. 

I'm going to close this issue for now but if you have any new issues/suggestions while you're using it feel free to open another. Thanks!

**Comment by jordymeow** [comment]
Hi @laurenashpole! I have just tried it and it works wonderfully. Thanks a lot for implementing this, this component is now really perfect for me :)
