### ISSUE TITLE
Function bind scope is "this" but is not clear what "this" is supposed to be

### ISSUE THREAD

**Issue by MaxdAyala** [laurenashpole/react-inner-image-zoom#100]
IIZ V3

This is a minor issue that doesn't affect any of the zoom behaviour as far as I can tell.

I noticed this when build the code with ESBuild and it produced a lint error for the bind scope.

The "this" bind scope appears not be used, and during build compilation gets abstracted away and is not used.

File: InnerImageZoom.js

```
  const handleClick = (e) => {
    if (isZoomed) {
      if (isTouch) {
        hideCloseButton && handleClose();
      } else {
        !isValidDrag && zoomOut();
      }

      return;
    }

    isTouch && setIsActive(true);

    if (zoomImg.current) {
      handleLoad({ target: zoomImg.current });
      zoomIn(e.pageX, e.pageY);
    } else {
      imgProps.current.onLoadCallback = zoomIn.bind(this, e.pageX, e.pageY);
    }
  };
```

Maybe the fix here is to replace "this" with "null".
It works for me to remove the lint error with ESBuild.

**Comment by laurenashpole** [comment]
It's common to use `this` with `bind` and this doesn't impact functionality so it's a question of personal preference.

**Comment by MaxdAyala** [comment]
Yes, no change in functionality because here it is an ES module where "this" has the initial value undefined.

The compiled code from the "lib" folder (extract below) shows "this" being set to undefined. Similarly for the "es" folder output.

```
"use strict";

var _this = void 0;

var handleClick = function handleClick(e) {
...
  imgProps.current.onLoadCallback = zoomIn.bind(_this, e.pageX, e.pageY);
}
```

Hence, no change in functionality, but someone like me might (mistakenly) read the code and think "this" has some value set by click handler.
