### ISSUE TITLE
Attribute IMG need receive variables or functions

### ISSUE THREAD

**Issue by tiagocardosoc** [laurenashpole/react-inner-image-zoom#111]
I was trying to add your component in my project but I face with a bug. The attribute "img" just receive a url link, but not a state variable or a function. Can you help with that? I really need it.

**Comment by laurenashpole** [comment]
Hi @tiagocardosoc, as of version 3.0.0 you should be able to use the `imgAttributes` prop to set any attributes that React allows on an `img` tag.
