### ISSUE TITLE
TypeError: Cannot read property 'removeEventListener' of null

### ISSUE THREAD

**Issue by jordymeow** [laurenashpole/react-inner-image-zoom#12]
Hi,

I found a little issue today. I am using NextJS, and I think this happens right before or after hydration. But maybe that also points at a potential memory leak.

It seems to happen here:
`_this.zoomImg.removeEventListener(_this.state.isTouch ? 'touchmove' : 'mousemove', _this.handleDragMove);`

In this case, I guess _handleDragEnd_ is called when, in fact, the component doesn't exist anymore. So this idea would be to unregister all the listeners as soon as the component is unmounted. 

Thanks :)

**Comment by laurenashpole** [comment]
Nice catch! 

I'd added a `handleDragEnd` trigger on mouse leave to handle an edge case if the user tried to drag the zoomed image out of the container. _However_, that meant it was possible for that to fire before the image had actually loaded. I just released a fix to check if the image is zoomed first.

**Comment by jordymeow** [comment]
Thanks a lot @laurenashpole! It works. It's really awesome you working on this so reactively! :)
