### ISSUE TITLE
Is there any way to make the component always active?

### ISSUE THREAD

**Issue by andyseracuse** [laurenashpole/react-inner-image-zoom#18]
I am creating a project which requires me to click on an image to enable an inner image zoom. I have created a conditional render that relies on an app level state to determine if the inner image zoom is enabled.  So basically, when I click on the image, the inner zoom component gets rendered with the mouse already on top of it.  This means that the "active" state of the zoom component isn't triggered because the mouseEnter event hasn't occured which means I have to move the mouse away from the image before the zoom functionality works.  I am wondering if there is a way for me to set that property so that it is permanently set to active?  Thanks so much for any help, this package has been so cool to work with!

**Comment by laurenashpole** [comment]
@andyseracuse Just released your fix for this in v1.3. Thanks for contributing!
