### ISSUE TITLE
how to fix if the image error when it load

### ISSUE THREAD

**Issue by vieyama** [laurenashpole/react-inner-image-zoom#35]
are there any properties like fallback to solve the failed image to load?

**Comment by laurenashpole** [comment]
Right now the component lets the browser handle broken images for the original image and should fail silently if the zoomed image doesn't load (it will also retry if the user tries to zoom in again). I would need to know more about your use case to figure out if this is a feature it would make sense to build in or if it's something that could be handled outside the component.

**Comment by akashdeepnandi** [comment]
I was using this library recently and faced this same issue, and I think everyone would want to handle broken image url gracefully, but as said by author of this library, it is not something that makes sense to add as a feature in this library. So potential solution I found was using a zero width image tag and using its onError callback for handling this.

`
import React from 'react';
import InnerImageZoom from "react-inner-image-zoom";

const test = () => {
    const [imgError, setImgError] = useState(false)
    return (
        <div>
            <img src={imgSrc} 
            alt="" 
            onError={() => setImgError(true)} 
            width={0} />
            <InnerImageZoom
              src={imgError ? fallbackImgSrc : imgSrc}
            // ...
            // other props
            // ...
            />
        </div>
    );
}

export default test;
`

Hope this helps.

**Comment by laurenashpole** [comment]
Thanks so much for the suggestion @akashdeepnandi! I think that approach makes the most sense so I'm going to close this issue for now.
