### ISSUE TITLE
Can a prop be added to hide the hint icon by default?

### ISSUE THREAD

**Issue by UlyssesInvictus** [laurenashpole/react-inner-image-zoom#36]
I can fork and submit a PR if necessary :)

Thanks for the great package!

**Comment by laurenashpole** [comment]
This is convenient timing! I would've asked for that PR but I've been working a big React hooks refactor that went out tonight so I threw this functionality in as well. You should be able to hide the icon using the `hideIcon` prop.

If you try it out, let me know if you run into any oddities in the new version. Thanks!
