### ISSUE TITLE
With zoomScale != 1, zooming multiple times is applying the zoom factor multiple times

### ISSUE THREAD

**Issue by ysavary** [laurenashpole/react-inner-image-zoom#38]
With zoomScale != 1, zooming multiple times is applying the zoom factor multiple times

https://github.com/laurenashpole/react-inner-image-zoom/blob/master/src/InnerImageZoom/InnerImageZoom.js#L77-L78

should use `naturalWidth` and `naturalHeight` ?

**Comment by laurenashpole** [comment]
Thanks for finding that @ysavary. I thought I'd done enough testing but totally missed the image scale when re-zooming without mousing out of the image first.

Let me know if you want to open a PR with the fixes you've already started.

**Comment by laurenashpole** [comment]
@ysavary That's awesome! Thanks for also including tests. As the bot said, this just went out with v2.0.1.
