### ISSUE TITLE
React.createElement: type is invalid - Check the render method of Image

### ISSUE THREAD

**Issue by davisjr2000** [laurenashpole/react-inner-image-zoom#4]
When placing 
`<InnerImageZoom src="https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png" />`
on my JSX, I get this error:

**React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.**

**Check the render method of Image.**

Maybe it is my Node version? I am using v6.17.1

**Comment by laurenashpole** [comment]
Hey @davisjr2000! I'm having trouble reproducing this issue, would you mind posting the code from your JSX file? I think this error is usually related to how a component is imported or exported but with more details I can help pinpoint exactly what's happening. Thanks!

**Comment by davisjr2000** [comment]
Hey @laurenashpole! I just figured it out.The problem is with my React version, "15.4.1"

This older version does not support `<React.Fragment>`

**Comment by laurenashpole** [comment]
Great. I should add a note about the minimum required React version to the README so thanks for flagging that.
