### ISSUE TITLE
hideHint is not working

### ISSUE THREAD

**Issue by nileshyadav326** [laurenashpole/react-inner-image-zoom#40]
hideHint={true} by adding this the glass icon does not remove

**Comment by laurenashpole** [comment]
Hey @nileshyadav326, I'm having trouble reproducing this. Could you confirm that you're on v2.0.0 of the package?

**Comment by kjrgreen** [comment]
@laurenashpole I'm experiencing this issue as well.
```
npm list | grep zoom
├── react-inner-image-zoom@2.0.0
```
I've imported styles.css as well. I'm using this together with Next.js, but that may be a red herring - styles.css is in my _app.jsx, so there should be no issue with that.

**Comment by laurenashpole** [comment]
`hideHint` should prevent the icon from rendering at all so the CSS shouldn't impact it. Would you mind pasting in a code example? I'm wondering if a combination of props is somehow the issue.

**Comment by kjrgreen** [comment]
`<InnerImageZoom src={src} alt={"Product image"} hideHint={true}/>`
This renders to, in Chrome:
`<figure class="iiz iiz--drag "><img class="iiz__img " src="redacted.jpg" alt="Product image" style="transition: opacity 0ms linear 0ms, visibility 150ms linear 0ms;"><span class="iiz__btn iiz__hint"></span></figure>`

**Comment by kjrgreen** [comment]
I cannot explain how, but the issue seemingly resolved itself - still on 2.0.0...
I've tried removing/adding back the stylesheet and it has no impact on this. I can no longer reproduce this.

**Comment by laurenashpole** [comment]
Great! I was wondering if it had something to do with the Next.js build process, I'll have to do some testing there when I have a chance. For now I'm going to close this issue, feel free to open it back up if you notice any other strange behavior.
