### ISSUE TITLE
react-inner-image-zoom only support PNG ?

### ISSUE THREAD

**Issue by career-ManimekalaiDevaraj** [laurenashpole/react-inner-image-zoom#46]
AM trying to apply this packages on png, jpg, jpeg, gif and bmp. It acts only on png.

**Comment by laurenashpole** [comment]
Hey @career-ManimekalaiDevaraj, 

The component definitely supports non-PNG image formats. If you take a look at the [demo page](https://laurenashpole.github.io/react-inner-image-zoom/), all the images there are JPGs. I would need to know more about how you're trying to use it to help debug.

**Comment by career-ManimekalaiDevaraj** [comment]
Hey hi @laurenashpole. Its working!! Thanks!!

**Comment by laurenashpole** [comment]
Yay! Glad to hear that, I'll go ahead and close this issue.
