### ISSUE TITLE
Zoom Image blank

### ISSUE THREAD

**Issue by abdulbasit12** [laurenashpole/react-inner-image-zoom#56]
I am using zoomType="hover". when I quickly move mouse on image, zoom image eventually gone blank and its not coming back until I take mouse out of image.

**Comment by laurenashpole** [comment]
Hey @abdulbasit12, I just published v2.0.2 which keeps the zoomed image in the DOM when `zoomPreload` is true. I would recommend using that when the `zoomType` is hover to avoid the image disappearing when it has to reload too many times. Let me know if that works for you!

**Comment by kireerik** [comment]
I can confirm that https://github.com/laurenashpole/react-inner-image-zoom/issues/56#issuecomment-861129064 is a workaround for #99.
