### ISSUE TITLE
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

### ISSUE THREAD

**Issue by samIntegrateur** [laurenashpole/react-inner-image-zoom#63]
Hello, I have found a (non-blocking) error in the console that is fired a lot of times while you move in the zoomed image in "touch mode". 
It happens when I'm using chrome with developer tools in "responsive" mode.

`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

**Comment by laurenashpole** [comment]
Thanks for flagging this! It may be causing other issues people are seeing around scrolling on mobile devices. I'll try to see if there's a quick fix over the weekend.

**Comment by laurenashpole** [comment]
This should be fixed in v2.0.3.
