### ISSUE TITLE
Slick Carousel slide changes under the zoomed image

### ISSUE THREAD

**Issue by eugene-khilay** [laurenashpole/react-inner-image-zoom#69]
When you are using zoom with Slick Carousel and `fullscreenOnMobile` property is true. It changes slides under the zoomed image when you swipe right or left.

Steps to reproduce:
- zoom first image of the slider
- drug zoomed image to the right
- close zoomed image
- the 2nd slide is active instead of the first

Reproducing on mobile devices.

**Comment by laurenashpole** [comment]
Hey @eugene-khilay, it took a while but this should be fixed in v3.0.0!
