### ISSUE TITLE
Test issues with version 2.0.3 when running against Chrome and Firefox

### ISSUE THREAD

**Issue by MaxdAyala** [laurenashpole/react-inner-image-zoom#71]
[zoom 2.0.3 tests fail on first run.txt](https://github.com/laurenashpole/react-inner-image-zoom/files/7022326/zoom.2.0.3.tests.fail.on.first.run.txt)
### Test issues with version 2.0.3

The tests are being run with PhantomJS. When the tests are run using Chrome or Firefox two of the tests fail. Since PhantomJS is no longer under development it would probably be a good idea to run against ChromeHeadless instead, or run against both.

The two failing tests are:

1. renders an image spacer if width, height, and hasSpacer are set
2. pans the zoomed image on mouse move

Fixes

1. Looks like floating point numbers are handled differently by PhantomJS so change the comparison operation to account for floating point differences.

```
it('renders an image spacer if width, height, and hasSpacer are set', () => {
  innerImageZoom({ width: 750, height: 500, hasSpacer: true });
  const wrapper = findRenderedDOMComponentWithTag(component, 'div');
  const paddingTop = wrapper.style['padding-top'];
  expect(paddingTop.substring(paddingTop.length - 1)).toBe('%');
  expect(Math.abs(66.67 - parseFloat(paddingTop))).toBeLessThan(0.05); // i.e. 100 x 500/750 %
  //expect(wrapper.style['padding-top']).toEqual('66.66666666666666%');
});
```

2. Change SRCS.zoomSrc to SRCS.zoom.
Since SRCS.zoomSrc doesn't exist this error could probably be detected by linting?

```
describe('move', () => {
  it('pans the zoomed image on mouse move', (done) => {
    //
[zoom 2.0.3 tests fail on first run.txt](https://github.com/laurenashpole/react-inner-image-zoom/files/7022289/zoom.2.0.3.tests.fail.on.first.run.txt)
innerImageZoom({ zoomSrc: SRCS.zoomSrc });
    innerImageZoom({ zoomSrc: SRCS.zoom });
    const figure = findRenderedDOMComponentWithTag(component, 'figure');
    Simulate.mouseEnter(figure);
    Simulate.click(figure, { pageX: 100, pageY: 100 });
    const zoomImg = findRenderedDOMComponentWithClass(component, 'iiz__zoom-img');
    zoomImg.onload = () => {
      const topPos = zoomImg.style.top;
      Simulate.mouseMove(figure, { pageX: 150, pageY: 150 });
      const updatedTopPos = zoomImg.style.top;
      expect(parseInt(topPos, 10)).toNotEqual(parseInt(updatedTopPos, 10));
      done();
    };
  });
});

```

The test output also produces a warning, probably for this test:

- hides the zoomed image on click on touch devices if hideCloseButton is true

I'm not sure at the moment what the fix is to remove the warning.

On startup when running tests from an IDE the first run after opening the IDE always fails with timeout errors. I haven't investigated these, but as a guess it may be a caching issue related to having to load the remote test images from unsplash.com. That is, a long delay the first time the images are requested, but subsequent requests being quicker due to caching.

Sample failed test run attached.

**Comment by laurenashpole** [comment]
Finally merged those fixes into v3.0.0.
