### ISSUE TITLE
Image object over src string

### ISSUE THREAD

**Issue by mhmoritz** [laurenashpole/react-inner-image-zoom#76]
I'd like to pass an `Image` object to the `src` attribute rather than a string, if that's possible?
This would allow registering callbacks such as `img.onload`.

Or any other exposure of the actual `Image` object would be great.

**Comment by laurenashpole** [comment]
This actually came up a couple weeks ago and I've been meaning to create a discussion around moving to an imgAttributes prop instead. I'm going to close this as an issue but I just started a thread [here](https://github.com/laurenashpole/react-inner-image-zoom/discussions/77) if you want to take a look at or comment on the proposal. 

Thank you for motivating me to kick that off!
