### ISSUE TITLE
No close hint with drag on mouse control

### ISSUE THREAD

**Issue by dzar-aker** [laurenashpole/react-inner-image-zoom#82]
When used on a touch device, there is a close hint/button in the upper right-hand corner of the zoomed image.

When using a mouse, however, and setting `moveType="drag"` on the component, there is no such button. It would be great if this would also be supported (and then extend the `hideCloseButton` to work with this, too).

**Comment by laurenashpole** [comment]
Hey @dzar-aker as of v3.0.0 the close button should be visible when the `moveType` is set to "drag".
