### ISSUE TITLE
Css 'cursor:zoom-in' property (.iiz) doesn't work

### ISSUE THREAD

**Issue by v-gourney** [laurenashpole/react-inner-image-zoom#90]
Can't change cursor property. It would be great to have 'cursor:zoom-in'  but it doesn't work.
Tested on Chrome and Firefox.

**Comment by laurenashpole** [comment]
The component currently has `cursor: zoom-in` set on hover when zoomed out (on class `.iiz`) and either `cursor: zoom-out` or `cursor: grab` when zoomed in depending on if the move type is pan or drag  (on class `.iiz__zoom-img--visible`) and it seems to be working on Chrome, Firefox, and Safari.

You should also be able to update those with custom cursor selections by adding your own CSS for those classes. If you're not seeing the originals or able to add your own, it sounds like something else in your project may be overriding the styling.
