### ISSUE TITLE
Missing transitive dependency to prop-types

### ISSUE THREAD

**Issue by Camorte** [laurenashpole/react-inner-image-zoom#95]
Received error "ModuleNotFoundError: Module not found: Error: Can't resolve 'prop-types' in '.../node_modules/react-inner-image-zoom/es/InnerImageZoom'". Solution: add "prop-types" package.

**Comment by laurenashpole** [comment]
Thanks for the heads up! I've never tested without `prop-types` available by default. I added it to the `peerDependencies` in version 3.0.1.
