### ISSUE TITLE
Inline style lengths should have a unit of px

### ISSUE THREAD

**Issue by MaxdAyala** [laurenashpole/react-inner-image-zoom#97]
There are some inline CSS styles that set length values that don't have a unit specified.
According to the CSS specs there should always be a unit, unless the value is 0.

In this case it looks like the unit should be pixels, px.

This affects:
InnerImageZoom.js : width property
ZoomImage.js : top and left properties

I've tried out fixes for these.

**Comment by laurenashpole** [comment]
According to the [React docs on style](https://reactjs.org/docs/dom-elements.html#style), the `px` is automatically appended for these properties so this is a matter of personal preference.

**Comment by MaxdAyala** [comment]
Yes, you are right, thanks. I thought it was producing a server render bug, but on retesting I can't reproduce any bug.
